# Generated by Django 2.2.7 on 2019-11-27 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='resourcegroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ResourceGroupName', models.CharField(max_length=100)),
                ('ResourceId', models.CharField(max_length=200)),
                ('Location', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'ResourceGroup',
            },
        ),
        migrations.CreateModel(
            name='resource',
            fields=[
                ('resourcegroup_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='azure.resourcegroup')),
                ('Name', models.CharField(max_length=100)),
                ('ResourceType', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Resource',
            },
            bases=('azure.resourcegroup',),
        ),
    ]
